const orderSetData = [
  {
    dependency: "https://github.com/PIH/openmrs-module-mirebalais",
    name: "CHOP",
    category: "CIEL:163073",
    id: 1,
    cycleCount: 6,
    cycleLength: 3,
    cycleLengthUnits: "Weeks",
    orders: [
      {
        drugName: "Strepsils",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Pint",
        dispensingQuantity: "3",
        reason: "",
        previousOrder: null,
        drugInstructions: "One tablet 3 Times daily",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "d656c4c5-6915-4bda-9023-e75cf80d4121",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
      {
        drugName: "SODIUM CHLORIDE",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Packets",
        dispensingQuantity: "2",
        reason: "",
        previousOrder: null,
        drugInstructions: "Sodium",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "9ec1b820-2e30-4bb1-9d18-2703e4c5f932",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
      {
        drugName: "Procold",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Pint",
        dispensingQuantity: "10",
        reason: "",
        previousOrder: null,
        drugInstructions: "2 thrice daily",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "502a2b2e-4659-4987-abbd-c50545dead47",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
    ],
  },
  {
    dependency: "https://github.com/PIH/openmrs-module-mirebalais",
    name: "COP",
    category: "CIEL:163073",
    id: 2,
    cycleCount: 6,
    cycleLength: 3,
    cycleLengthUnits: "Weeks",
    orders: [
      {
        drugName: "Vitamin C",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Packet",
        dispensingQuantity: "5",
        reason: "",
        previousOrder: null,
        drugInstructions: "Two tablet 2 Times daily",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "d656c4c5-6915-4bda-9023-e75cf80d4121",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
      {
        drugName: "Panadol",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Packets",
        dispensingQuantity: "3",
        reason: "",
        previousOrder: null,
        drugInstructions: "Sodium",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "9ec1b820-2e30-4bb1-9d18-2703e4c5f932",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
      {
        drugName: "Flagin",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Pint",
        dispensingQuantity: "10",
        reason: "",
        previousOrder: null,
        drugInstructions: "2 thrice daily",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "502a2b2e-4659-4987-abbd-c50545dead47",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
    ],
  },
  {
    dependency: "https://github.com/PIH/openmrs-module-mirebalais",
    name: "CMF",
    category: "CIEL:163073",
    id: 3,
    cycleCount: 8,
    cycleLength: 3,
    cycleLengthUnits: "Weeks",
    orders: [
      {
        drugName: "Anacin",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Packet",
        dispensingQuantity: "1",
        reason: "",
        previousOrder: null,
        drugInstructions: "Two tablet 2 Times daily",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "d656c4c5-6915-4bda-9023-e75cf80d4121",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
      {
        drugName: "Pentax",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Packets",
        dispensingQuantity: "6",
        reason: "",
        previousOrder: null,
        drugInstructions: "Sodium",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "9ec1b820-2e30-4bb1-9d18-2703e4c5f932",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
      {
        drugName: "Cerates",
        action: "NEW",
        dose: "",
        dosingUnit: "",
        frequency: "",
        route: "",
        duration: "",
        durationUnit: "",
        dispensingUnit: "Pint",
        dispensingQuantity: "10",
        reason: "",
        previousOrder: null,
        drugInstructions: "2 thrice daily",
        careSetting: "6f0c9a92-6f24-11e3-af88-005056821db0",
        drug: "502a2b2e-4659-4987-abbd-c50545dead47",
        orderer: "f9badd80-ab76-11e2-9e96-0800200c9a66",
        dosingType: "org.openmrs.FreeTextDosingInstructions",
        type: "drugorder",
      },
    ],
  },
];

export default orderSetData;