export const SET_LOCATIONS = "SET_LOCATIONS";
export const SET_CURRENT_SESSION = "SET_CURRENT_SESSION";
export const SET_PATIENT = "SET_PATIENT";
export const SET_NOTE = "SET_NOTE";
export const FETCH_ORDER_CONFIG_SUCCESS = 'FETCH_ORDER_CONFIG_SUCCESS';
export const FETCH_ORDER_CONFIG_FAILURE = 'FETCH_ORDER_CONFIG_FAILURE';
export const FETCH_ORDER_CONFIG_LOADING = 'FETCH_ORDER_CONFIG_LOADING';
